from datetime import datetime, timezone

from aegis.models.state import AegisState, RunEvent


def generate_report(state: AegisState) -> str:
    """Generate a Markdown training report from the current pipeline state."""
    model_name = state.spec.model_name if state.spec else "unknown"
    timestamp_str = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")

    report = f"""# Aegis-ML Training Report

**Run ID:** {model_name.split('/')[-1]}-{timestamp_str}
**Generated:** {datetime.now(timezone.utc).isoformat()}

---

## Executive Summary

| Metric | Value |
|--------|-------|
"""
    if state.spec:
        report += f"| Model | {state.spec.model_name} |\n"
        report += f"| Method | {state.spec.method} |\n"
    if state.cost_estimate:
        report += (
            f"| Estimated Cost | ${state.cost_estimate.estimated_cost_usd:.4f} |\n"
        )
        report += (
            f"| Est. VRAM | {state.cost_estimate.estimated_vram_gb:.1f} GB |\n"
        )
        report += (
            f"| Est. Duration | {state.cost_estimate.estimated_duration_min:.1f} min |\n"
        )
    if state.execution_result:
        duration_sec = state.execution_result.get("duration_sec")
        if duration_sec is not None:
            report += f"| Actual Duration | {duration_sec / 60:.1f} min |\n"
    if state.eval_result:
        status_icon = "PASSED" if state.eval_result.get("passed") else "FAILED"
        report += f"| Status | {status_icon} |\n"

    report += "\n---\n\n## Training Specification\n\n"
    if state.spec:
        report += f"```json\n{state.spec.model_dump_json(indent=2)}\n```\n"

    report += "\n---\n\n## Cost Gate Decision\n\n"
    report += "| Threshold | Value |\n|-----------|-------|\n"
    report += f"| Soft Limit | ${state.budget_policy.soft_threshold_usd:.2f} |\n"
    report += f"| Hard Limit | ${state.budget_policy.max_budget_usd:.2f} |\n"
    if state.cost_estimate:
        report += f"| Estimated | ${state.cost_estimate.estimated_cost_usd:.4f} |\n"
        if (
            state.cost_estimate.estimated_cost_usd
            < state.budget_policy.soft_threshold_usd
        ):
            decision = "AUTO-APPROVED"
        elif state.human_decision:
            decision = f"HUMAN-APPROVED ({state.human_decision})"
        else:
            decision = "PENDING"
        report += f"| Decision | {decision} |\n"

    report += "\n---\n\n## Event Timeline\n\n"
    report += "| Time | Phase | Status | Message |\n"
    report += "|------|-------|--------|---------|\n"
    for event in state.events:
        time_str = event.timestamp.strftime("%H:%M:%S")
        report += f"| {time_str} | {event.phase} | {event.status} | {event.message} |\n"

    if state.eval_result and state.eval_result.get("failures"):
        report += "\n---\n\n## Evaluation Failures\n\n"
        for failure in state.eval_result["failures"]:
            report += f"- {failure}\n"

    report += "\n---\n\n*Generated by Aegis-ML - Production-Grade AI Reliability Engineer*"
    return report


def write_report_node(state: AegisState) -> AegisState:
    """Generate the final Markdown report and attach it to state."""
    try:
        report = generate_report(state)
        event = RunEvent(
            phase="write_report",
            status="completed",
            message=f"Generated report ({len(report)} chars)",
        )
        return state.model_copy(
            update={
                "final_report": report,
                "events": state.events + [event],
            }
        )
    except Exception as e:
        event = RunEvent(
            phase="write_report",
            status="failed",
            message=f"Report generation failed: {str(e)}",
        )
        return state.model_copy(update={"events": state.events + [event]})
